apiVersion: v1
kind: BuildConfig
metadata:
  name: build-with-tag
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'git://github.com/patrickeasters/openshift-build-test.git'
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: 'BUILD_LOGLEVEL'
          value: '5'
